import Head from 'next/head';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import Link from 'next/link';
import { useDispatch } from 'react-redux';
import { setAuthToken, setIsAuthenticated, setUserId } from '@/store/user';
import { useEffect } from 'react';
import { UserAuthResponseUserDataType } from '@/utils/types';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const dispatch = useDispatch();

  const handleCheckAuthStatus = () => {
    const user = localStorage.getItem('user');
    const userData: UserAuthResponseUserDataType = user? JSON.parse(user) : '';
    if (user) {
      dispatch(setIsAuthenticated(true));
      dispatch(setUserId(userData.id));
      dispatch(setAuthToken(userData.token))
    } else {
      dispatch(setIsAuthenticated(false));
      dispatch(setUserId(''));
      dispatch(setAuthToken(''))
    }
  };

  useEffect(() => {
    handleCheckAuthStatus();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='min-h-screen flex flex-col justify-around items-center'>
        <Script src='https://accounts.google.com/gsi/client' async defer />
        <div className='flex flex-col md:flex-row w-[70%] sm:w-[300px] gap-6 text-lg'>
          <Link href='/events'>
            <button className='rounded-lg bg-slate-500 text-white w-full hover:bg-slate-400 hover:scale-105 transition-all duration-200'>
              Events
            </button>
          </Link>
          <Link href='/post-event'>
            <button className='rounded-lg bg-slate-500 text-white w-full hover:bg-slate-400 hover:scale-105 transition-all duration-200'>
              Post Event
            </button>
          </Link>
        </div>
      </main>
    </>
  );
}
